/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aejedgematching;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.PrintStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.UIManager;
/**
 *
 * @author Usuario
 */
public class JEdgeMatchingUI extends javax.swing.JFrame {

   
    JPanelEdge pnlPuzzle;
    
    private final String ACTION_COMMAND_CONFIG = "ACTION_COMMAND_CONFIG";
    private final String ACTION_COMMAND_NUEVO = "ACTION_COMMAND_NUEVO";
    private final String ACTION_COMMAND_ROTAR = "ACTION_COMMAND_ROTAR";
    private final String ACTION_COMMAND_CAMBIAR = "ACTION_COMMAND_CAMBIAR";
    private final String ACTION_COMMAND_MEZCLAR = "ACTION_COMMAND_MEZCLAR";
    private final String ACTION_COMMAND_GUARDAR = "ACTION_COMMAND_GUARDAR";
    private final String ACTION_COMMAND_CARGAR = "ACTION_COMMAND_CARGAR";

    JLabel lblDim;
    JTextField txtDim;
    JLabel lblColor;
    JTextField txtColor;
    JButton btnCambiarConfig;
    
    JPanel pnlVisualizacion;
    
    JButton btnNuevo;
    JButton btnRotar;
    JButton btnCambiar;
    JButton btnMezclar;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JEdgeMatchingUI() {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception ex) {
                }

                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                setLayout(new GridBagLayout());
                
                ActionListener actionListener = new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        
                        ficha[][] tablero = pnlPuzzle.getTablero();
                        boolean cargarTablero = true;
                        
                        switch (e.getActionCommand()){
                            
                            case ACTION_COMMAND_CONFIG:
                                JDialog pop = new JDialog();
                                pop.add(new JPanelConfig(JEdgeMatchingUI.this, Parametros.DIMENSION_TABLERO, Parametros.MAX_COLOR));
                                pop.setModal(true);
                                pop.setMinimumSize(new Dimension(230, 180));
                                pop.setMaximumSize(new Dimension(230, 180));
                                pop.setSize(new Dimension(230, 180));
                                pop.setPreferredSize(new Dimension(230, 180));
                                pop.setLocationRelativeTo(null);
                                pop.setVisible(true);
                                cargarTablero = false;
                                break;
                                
                            case ACTION_COMMAND_NUEVO:
                                tablero = generarPuzle();
                                break;
                                
                            case ACTION_COMMAND_ROTAR:
                                tablero = rotarFichasPuzle(tablero);
                                break;
                                
                            case ACTION_COMMAND_CAMBIAR:
                                tablero = cambiarFichasPuzle(tablero);
                                break;
                                
                            case ACTION_COMMAND_MEZCLAR:
                                tablero = rotarFichasPuzle(tablero);
                                tablero = cambiarFichasPuzle(tablero);
                                break;
                                
                            case ACTION_COMMAND_GUARDAR:
                                guardarArchivo(tablero);
                                cargarTablero = false;
                                break;
                                
                            case ACTION_COMMAND_CARGAR:
                                cargarArchivo();
                                break;
                        }
                        if (cargarTablero){
                            pnlPuzzle.setTablero(tablero);
                            pnlPuzzle.cargarTablero();
                        }
                    }
                };
                
                GridBagConstraints c = new GridBagConstraints();
                
                JMenuBar menu = new JMenuBar();
                
                //MENU CONFIGURACION
                JMenu menuConfig = new JMenu("Configuración");
                menu.add(menuConfig);
                
                JMenuItem itConfig = new JMenuItem("Cambiar");
                itConfig.addActionListener(actionListener);
                itConfig.setActionCommand(ACTION_COMMAND_CONFIG);
                menuConfig.add(itConfig);

                //MENU PUZLE
                JMenu menuPuzle = new JMenu("Puzle");
                menu.add(menuPuzle);

                JMenuItem itNuevo = new JMenuItem("Nuevo");
                itNuevo.addActionListener(actionListener);
                itNuevo.setActionCommand(ACTION_COMMAND_NUEVO);
                menuPuzle.add(itNuevo);
                
                JSeparator sep1 = new JSeparator();
                menuPuzle.add(sep1);
                
                JMenuItem itRotar = new JMenuItem("Rotar");
                itRotar.addActionListener(actionListener);
                itRotar.setActionCommand(ACTION_COMMAND_ROTAR);
                menuPuzle.add(itRotar);
                
                JMenuItem itCambiar = new JMenuItem("Cambiar");
                itCambiar.addActionListener(actionListener);
                itCambiar.setActionCommand(ACTION_COMMAND_CAMBIAR);
                menuPuzle.add(itCambiar);
                
                JMenuItem itMezclar = new JMenuItem("Mezclar");
                itMezclar.addActionListener(actionListener);
                itMezclar.setActionCommand(ACTION_COMMAND_MEZCLAR);
                menuPuzle.add(itMezclar);

                //MENU ARCHIVO
                JMenu menuArchivo = new JMenu("Archivo");
                menu.add(menuArchivo);
                
                JMenuItem itGuardar = new JMenuItem("Guardar");
                itGuardar.addActionListener(actionListener);
                itGuardar.setActionCommand(ACTION_COMMAND_GUARDAR);
                menuArchivo.add(itGuardar);
                
                JSeparator sep2 = new JSeparator();
                menuArchivo.add(sep2);
                
                JMenuItem itCargar = new JMenuItem("Cargar");
                itCargar.addActionListener(actionListener);
                itCargar.setActionCommand(ACTION_COMMAND_CARGAR);
                menuArchivo.add(itCargar);

                c.fill = GridBagConstraints.HORIZONTAL;
                c.gridy = 0;
                c.gridx = 0;
                add(menu, c);
                                
                pnlVisualizacion = new JPanel(new GridBagLayout());
                
                c.fill = GridBagConstraints.HORIZONTAL;
                
                ficha[][] tablero = generarPuzle();
                pnlPuzzle = new JPanelEdge(Parametros.DIMENSION_TABLERO, tablero);
                pnlPuzzle.validate();
                pnlPuzzle.repaint();
                pnlVisualizacion.add(pnlPuzzle);
                
                c.fill = GridBagConstraints.BOTH;
                c.gridy = 1;
                c.gridx = 0;
                c.weightx = 1;
                c.weighty = 1;
                add(pnlVisualizacion, c);
                                
                pack();
                setLocationRelativeTo(null);
                setExtendedState(JFrame.MAXIMIZED_BOTH);
                setVisible(true);
            }
        });
    }
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new JEdgeMatchingUI();
    }

    public void cambiarConfiguracion(){
        ficha[][] tablero = generarPuzle();
        pnlVisualizacion.remove(pnlPuzzle);
        pnlPuzzle = null;
        pnlPuzzle = new JPanelEdge(Parametros.DIMENSION_TABLERO, tablero);
        pnlVisualizacion.add(pnlPuzzle);
        pnlVisualizacion.validate();
        pnlVisualizacion.repaint();
    }
    
    private static ficha[][] iniciarPuzle(){
        
        int nroPieza = 1;
        ficha[][] tablero = new ficha[Parametros.DIMENSION_TABLERO][Parametros.DIMENSION_TABLERO];

        for (int fila = 0; fila < Parametros.DIMENSION_TABLERO; fila++){
            for (int columna = 0; columna < Parametros.DIMENSION_TABLERO; columna++){
                int[] colores = new int[Parametros.CANT_COLOR_FICHA];
                for (int patron = 0; patron < Parametros.CANT_COLOR_FICHA; patron++){
                    colores[patron] = 0;
                }
                
                ficha nuevaFicha = new ficha(nroPieza, colores);
                tablero[fila][columna] = nuevaFicha;
                nroPieza++;
            }
        }
        
        return tablero;
    }
    
    private ficha[][] generarPuzle(){
        
        int nroPieza = 1;
        ficha[][] tablero = new ficha[Parametros.DIMENSION_TABLERO][Parametros.DIMENSION_TABLERO];
        
        int indiceEsquinas = 0;
        int indiceBordes = 0;
        int filaInterior = 0, columnaInteriro = 0;
        ficha[] esquinas = new ficha[4];
        ficha[] bordes = new ficha[(Parametros.DIMENSION_TABLERO - 2) * 4];
        ficha[][] interior = new ficha[Parametros.DIMENSION_TABLERO - 2][Parametros.DIMENSION_TABLERO - 2];
        
        
        for (int fila = 0; fila < Parametros.DIMENSION_TABLERO; fila++){
            for (int columna = 0; columna < Parametros.DIMENSION_TABLERO; columna++){
                int[] colores = new int[Parametros.CANT_COLOR_FICHA];
                for (int patron = 0; patron < Parametros.CANT_COLOR_FICHA; patron++){
                    colores[patron] = 1 + (int)(Math.random() * Parametros.MAX_COLOR);
                }
                if (fila == 0){
                    colores[0] = 0;
                }else{
                    colores[0] = tablero[fila-1][columna].getColores()[2];
                    if (fila == Parametros.DIMENSION_TABLERO - 1){
                        colores[2] = 0;
                    }
                }
                
                if (columna == 0){
                    colores[3] = 0;
                }else {
                    colores[3] = tablero[fila][columna-1].getColores()[1];
                    if (columna == Parametros.DIMENSION_TABLERO - 1){
                        colores[1] = 0;
                    }
                }
                
                //para prueba
//                if ((i == Parametros.DIMENSION - 1) && (j == Parametros.DIMENSION - 1)){
//                    colores[3] = 10;
//                }
                
                ficha nuevaFicha = new ficha(nroPieza, colores);
                tablero[fila][columna] = nuevaFicha;
                nroPieza++;
                
                if ((fila == 0) || (fila == Parametros.DIMENSION_TABLERO - 1) ||
                        (columna == 0) || (columna == Parametros.DIMENSION_TABLERO - 1)){
                    if ((fila == columna) || (fila + columna == Parametros.DIMENSION_TABLERO - 1)){
                        esquinas[indiceEsquinas] = nuevaFicha;
                        indiceEsquinas++;
                    }else{
                        bordes[indiceBordes] = nuevaFicha;
                        indiceBordes++;
                    }
                }else{
                    interior[filaInterior][columnaInteriro] = nuevaFicha;
                    columnaInteriro++;
                    if (columnaInteriro > Parametros.DIMENSION_TABLERO - 3){
                        filaInterior++;
                        columnaInteriro = 0;
                    }
                }
            }
        }
        
//        Individuo ind = new Individuo(esquinas, bordes, interior);
//        AE ae = new AE();
//        System.out.println("++++++++++++++++++++++");
//        for (int i = 0; i < 20; i++){
//            ae.cruzamiento(ind, ind);
//            System.out.println("----------------------");
//        }
//        System.out.println("++++++++++++++++++++++");
//        System.out.println("Prob. cambio: " + ind.getFitness());
//        System.out.println("Prob. cambio: " + ind.getFitness());

//        System.out.println("───────────────────────────────────");
//        for (int fila = 0; fila < Parametros.DIMENSION; fila++){
//            for (int columna = 0; columna < Parametros.DIMENSION; columna++){
//                System.out.print("│  ");
//                if (tablero[fila][columna].getColores()[0] < 10){
//                    System.out.print("0");
//                }
//                System.out.print(tablero[fila][columna].getColores()[0] + "  ");
//            }
//
//            System.out.println("│");
//            for (int columna = 0; columna < Parametros.DIMENSION; columna++){
//                System.out.print("│");
//                if (tablero[fila][columna].getColores()[3] < 10){
//                    System.out.print("0");
//                }
//                System.out.print(tablero[fila][columna].getColores()[3] + "  ");
//                if (tablero[fila][columna].getColores()[1] < 10){
//                    System.out.print("0");
//                }
//                System.out.print(tablero[fila][columna].getColores()[1]);
//            }
//            System.out.println("│");
//
//            for (int columna = 0; columna < Parametros.DIMENSION; columna++){
//                System.out.print("│  ");
//                if (tablero[fila][columna].getColores()[2] < 10){
//                    System.out.print("0");
//                }
//                System.out.print(tablero[fila][columna].getColores()[2] + "  ");
//            }
//            System.out.println("│");
//            System.out.println("───────────────────────────────────");
//        }
        
        return tablero;
    }
    
    private ficha[][] rotarFichasPuzle(ficha[][] tablero){
        
        int rotacion;
        
        for (int fila = 0; fila < Parametros.DIMENSION_TABLERO; fila++){
            for (int columna = 0; columna < Parametros.DIMENSION_TABLERO; columna++){
                rotacion = (int)(Math.random() * 4);
                tablero[fila][columna].rotarFicha(rotacion);
            }
        }
        return tablero;
        
    }

    private ficha[][] cambiarFichasPuzle(ficha[][] tablero){
        
        int filaSeleccionada, columnaSeleccionada, probabilidadCambio;
        ficha fichaSeleccionada;
        
        for (int fila = 0; fila < Parametros.DIMENSION_TABLERO; fila++){
            for (int columna = 0; columna < Parametros.DIMENSION_TABLERO; columna++){
                if (!tablero[fila][columna].isCambioPosicion()){
                    probabilidadCambio = (int)(Math.random() * 10);
                    if (probabilidadCambio > 2){
                        tablero[fila][columna].setCambioPosicion(true);
                        filaSeleccionada = (int)(Math.random() * Parametros.DIMENSION_TABLERO);
                        columnaSeleccionada = (int)(Math.random() * Parametros.DIMENSION_TABLERO);
                        fichaSeleccionada = tablero[filaSeleccionada][columnaSeleccionada];
                        tablero[filaSeleccionada][columnaSeleccionada] = tablero[fila][columna];
                        tablero[fila][columna] = fichaSeleccionada;
                    }
                }
            }
        }
        
        for (int fila = 0; fila < Parametros.DIMENSION_TABLERO; fila++){
            for (int columna = 0; columna < Parametros.DIMENSION_TABLERO; columna++){
                tablero[fila][columna].setCambioPosicion(false);
            }
        }
        
        return tablero;
    }
    
    public int getHeightTablero(){
        return pnlPuzzle.getHeight();
    }
    
    private void guardarArchivo(ficha[][] tablero){

        FileOutputStream fos = null;
        PrintStream ps = null;
        String path = System.getProperty("user.dir");
        DateFormat format = new SimpleDateFormat("YYYYMMdHm");
        path += "/Edge" + format.format(new Date()) + ".txt";
        
        try{
            fos = new FileOutputStream(path);
            ps = new PrintStream(fos);
            
            for (int fila = 0; fila < Parametros.DIMENSION_TABLERO; fila++){
                for (int columna = 0; columna < Parametros.DIMENSION_TABLERO; columna++){
                    for (int patron = 0; patron < Parametros.CANT_COLOR_FICHA; patron++){
                        ps.print(tablero[fila][columna].getColores()[patron]);
                        if (patron != Parametros.CANT_COLOR_FICHA - 1){
                            ps.print(" ");
                        }
                    }
                    if ((fila != Parametros.DIMENSION_TABLERO - 1) || (columna != Parametros.DIMENSION_TABLERO - 1)){
                        ps.println();
                    }
                }
            }
        }catch(FileNotFoundException ex){
            System.out.println(ex.getMessage());
        }finally{
            if (ps != null){
                ps.flush();
                ps.close();
            }
            try{
                if (fos != null){
                    fos.flush();
                    fos.close();
                }
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
        }
    }
    
    private void cargarArchivo(){
        try{
            JFileChooser fc = new JFileChooser();
            int retVal = fc.showOpenDialog(JEdgeMatchingUI.this);
        
            switch(retVal){
                case JFileChooser.APPROVE_OPTION:
                    File f = fc.getSelectedFile();
                    BufferedReader br = new BufferedReader(new FileReader(f));
                    String l;
                    int nroFicha = 1;
                    int fila = 0;
                    int columna = 0;
                    ficha[] esquinas = new ficha[4];
                    ficha[] bordes = new ficha[(Parametros.DIMENSION_TABLERO - 2) * 4];
                    ficha[][] interior = new ficha[Parametros.DIMENSION_TABLERO - 2][Parametros.DIMENSION_TABLERO - 2];
                    ArrayList<ficha> fichas = new ArrayList<>();
                    
                    while ((l = br.readLine()) != null){
                        System.out.println(l);
                        String[] col = l.split(" ");
                        int[] colores = new int[Parametros.CANT_COLOR_FICHA];
                        for (int patron = 0; patron < Parametros.CANT_COLOR_FICHA; patron++){
                            colores[patron] = Integer.parseInt(col[patron]);
                        }
                        ficha fichaN = new ficha(nroFicha, colores);
                        
                    }
                    br.close();
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "No se seleccionó ningún archivo", "Cargar archivo", JOptionPane.WARNING_MESSAGE);
                    break;
            }
        }catch(Exception ex){}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel pnl;
    // End of variables declaration//GEN-END:variables
}
